/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppAttendanceRouteImport } from './routes/_app/attendance'
import { Route as AppCirclesRouteImport } from './routes/_app/circles'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppStudentsRouteImport } from './routes/_app/students'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppCirclesRoute = AppCirclesRouteImport.update({
  id: '/circles',
  path: '/circles',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AppAttendanceRoute
  '/circles': typeof AppCirclesRoute
  '/dashboard': typeof AppDashboardRoute
  '/reports': typeof AppReportsRoute
  '/students': typeof AppStudentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AppAttendanceRoute
  '/circles': typeof AppCirclesRoute
  '/dashboard': typeof AppDashboardRoute
  '/reports': typeof AppReportsRoute
  '/students': typeof AppStudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/circles': typeof AppCirclesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/students': typeof AppStudentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/attendance' | '/circles' | '/dashboard' | '/reports' | '/students'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/attendance' | '/circles' | '/dashboard' | '/reports' | '/students'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/attendance'
    | '/_app/circles'
    | '/_app/dashboard'
    | '/_app/reports'
    | '/_app/students'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/circles': {
      id: '/_app/circles'
      path: '/circles'
      fullPath: '/circles'
      preLoaderRoute: typeof AppCirclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppCirclesRoute: typeof AppCirclesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppReportsRoute: typeof AppReportsRoute
  AppStudentsRoute: typeof AppStudentsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppCirclesRoute: AppCirclesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppReportsRoute: AppReportsRoute,
  AppStudentsRoute: AppStudentsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
